# job_environment will setup the environment for any job being executed.
job_environment: &job_environment
  NODE_ENV: test

# job_defaults applies all the defaults for each job.
job_defaults: &job_defaults
  working_directory: ~/coralproject/rte
  docker:
    - image: circleci/node:8
  environment:
    <<: *job_environment

version: 2
jobs:
  # npm_dependencies will install the dependencies used by all other steps.
  npm_dependencies:
    <<: *job_defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/coralproject/rte
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Update NPM
          command: sudo npm update -g npm
      - run:
          name: Audit dependencies
          command: npm audit
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules

  # lint will perform file linting.
  lint:
    <<: *job_defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/coralproject/rte
      - run:
          name: Perform linting
          command: npm run lint

  # build will build the static assets and server typescript files.
  build:
    <<: *job_defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/coralproject/rte
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - npm_dependencies
      - lint:
          requires:
            - npm_dependencies
      - build:
          requires:
            - npm_dependencies
