version: 2.1
orbs:
  node: circleci/node@4.1.0
executors:
  default:
    docker:
      - image: cimg/node:18.16.0
    working_directory: ~/repo
jobs:
  dependencies:
    executor: default
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    executor: default
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint Source Code
          command: npm run lint
      - run:
          name: Build Source Code
          command: npm run build
      - run:
          name: Lint Versions
          command: npx @coralproject/package-version-lint
  release:
    executor: default
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Verify release version
          command: npx @coralproject/package-version-lint --expect ${CIRCLE_TAG/#v}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

# filter_release will add the filters for a deploy job in a workflow to make it
# only execute on a tagged release.
filter_release: &filter_release
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

workflows:
  test:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
  test-deploy:
    jobs:
      - dependencies:
          <<: *filter_release
      - test:
          <<: *filter_release
          requires:
            - dependencies
      - release:
          <<: *filter_release
          requires:
            - test
